app1/urls.py
from django.urls import path
from app1.views import *
app_name='pooji'
urlpatterns=[
    path('janu/',janu,name='janu'),
]

project20/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
from app2.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('meghana/',meghana,name='meghana'),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def janu(request):
    return render(request,'janu.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def meghana(request):
    return render(request,'meghana.html')

templates/janu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>welcome janu file</h1>
        <h2><a href="{% url 'meghana' %}">meghana</a></h2>
    </center>
</body>
</html>

templates/meghana.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>welcome meghana</h1>
        <h2><a href="{% url 'pooji:janu' %}">click hear togo janu page</a></h2>
    </center>
</body>
</html>